### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sgkimsm** [dwatling/athena#1]
Hi,

Thank you for sharing great work, but I got small issue with Athena.
Athena mytestproject throw java.lang.StringIndexOutOfBoundsException exception as below.
# 

Begin Athena

Found 3 test suites.
Running 11 test(s) for com.example.ActTest: Except
ion in thread "main" java.lang.StringIndexOutOfBoundsException: String index out
 of range: -2
        at java.lang.String.substring(Unknown Source)
        at java.lang.String.substring(Unknown Source)
        at com.synaptik.athena.AthenaTestResult.parse(AthenaTestResult.java:98)
        at com.synaptik.athena.Athena.runCommand(Athena.java:159)
        at com.synaptik.athena.Athena.run(Athena.java:73)
#         at com.synaptik.athena.Athena.main(Athena.java:49)

When I execute the test suite using "adb shell am instrument ...", test fails with
# 

com.example.ActTest:
Failure in test01:
junit.framework.AssertionFailedError
        at com.example.ActTest.commonxxx(ActTest.java:68)
        at com.example.ActTest.test01(ActTest.java:73)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:205)
        at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:195)
        at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:175)
        at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
        at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
        at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:444)
#         at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1447)

I think you should check the line length before call "failure = line.substring(AFE.length() + 2);" in AthenaTestResult.java, but I'm not sure.
I'm new to Java world, so I don't know how I can build jar file from the source.

Thank you.

**Comment by sgkimsm** [comment]
I'm not sure my approach is right, but it works

# 

 if (line.length()>AFE.length()+2 )
    failure = line.substring(AFE.length() + 2);
 else
    failure = "";

#
